### PR TITLE
disable plotbot standup feature

### PR DESCRIPTION
**Pull request by bpostlethwaite**
cc @nicolaskruchten @scjody 

Tried it out with a QA bot. Does at is suggests.

### CODE REVIEW

**Comment by bpostlethwaite** [comment]
Once this is merged I'll deploy. Been a while tho :crossed_fingers:

**Comment by bpostlethwaite** [comment]
k @scjody any chance you can deploy this thing out to Plotbot once it is in? I just spent 30 minutes fumbling around trying to get `ansible-playbook` and `plotly_gce` to function properly and failed. If it's an easy deploy for you can you run that once this is merged?
Something like:
```
ansible-playbook ../streambed/deployment/tools/plotly_gce playbook_plotbot.yml --tags updt_plotbot
```
?

If it isn't, I'll keep fumbling around :)

**Comment by nicolaskruchten** [comment]
Can we tell Plotbot to just not be in #plotly instead? or does that also require a redeploy?

**Comment by scjody** [comment]
> Can we tell Plotbot to just not be in #plotly instead? or does that also require a redeploy?

I'm not sure that's possible given Plotbot's current design, and it looks like Ben's change will fix the issue.

@bpostlethwaite Sure, once you've merged I'll try deploying this.

**Comment by bpostlethwaite** [comment]
OK @scjody we're :ok_hand: to deploy

**Comment by scjody** [comment]
OK, deploying.

**Comment by scjody** [comment]
Screen Shot 2019-05-07 at 9 53 11

**Pull request merged**
